app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');

Route::get('/dashboard', [
    'middleware' => 'auth',
    'uses' => 'DashboardController@index'
]);

Route::get('/callback', [
    'middleware' => 'auth',
    'uses' => 'DashboardController@callback'
]);

Route::get('/dashboard/ddc', [
    'middleware' => 'auth',
    'uses' => 'DashboardController@ddc'
]);

Route::get('/dashboard/survey', [
    'middleware' => 'auth',
    'uses' => 'DashboardController@survey'
]);

Route::get('/dashboard/survey/{daerah}', [
    'middleware' => 'auth',
    'uses' => 'DashboardController@surveyByDaerah'
]);

Route::get('/dashboard/ddc/test', [
    'middleware' => 'auth',
    'uses' => 'DashboardController@ddctest'
]);

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

Route::resource('sms', 'SmsController');

Route::get('api/sms/all', 'ApiSmsController@index');
Route::get('api/sms/read', 'ApiSmsController@read');
Route::get('api/sms/unread', 'ApiSmsController@unread');
Route::get('api/sms/{area}/daily', 'ApiSmsController@dailySms');
Route::post('api/sms/new', 'ApiSmsController@newSms');
Route::get('api/sms/new', 'ApiSmsController@newSms');

Route::get('api/ddc/aggregates', 'ApiSmsController@aggregates');
Route::get('api/ddc/aggregates/{questionId}','ApiSmsController@aggByQuestionId');
Route::get('api/ddc/aggregates/sender{format?}', 'ApiSmsController@aggSender');
Route::get('api/ddc/aggregates/sender/daily', 'ApiSmsController@aggSenderDaily');
Route::get('api/ddc/aggregates/sender/daily/graph', 'ApiSmsController@aggSenderDailyGraph');
Route::get('api/ddc/aggregates/sender/{date}', 'ApiSmsController@aggSenderWithDate');
Route::get('api/ddc/aggregates/bydate', 'ApiSmsController@aggByDate');

Route::get('api/survey/{daerah}/aggregates', 'ApiSmsController@surveyAggByDaerah');

Route::get('api/survey/{daerah}/dashboard/agg/{nomor}', 'ApiSmsController@surveyAggForDashboard');
Route::get('api/survey/{daerah}/dashboard/sms', 'ApiSmsController@surveySmsForDashboard');
Route::get('api/survey/{daerah}/dashboard/sender', 'ApiSmsController@surveySenderForDashboard');
Route::get('api/survey/{daerah}/dashboard/percentage', 'ApiSmsController@surveyPercentageForDashboard');
Route::get('api/survey/{daerah}/dashboard/gauge', 'ApiSmsController@surveyForDashboardGauge');
Route::get('api/survey/{daerah}/dashboard/{nomor}', 'ApiSmsController@surveyForDashboard');

Route::get('api/research/{id}/dashboard/gauge', 'ApiSmsController@researchForDashboardGauge');
Route::get('api/research/{id}/dashboard/{nomor}', 'ApiSmsController@researchForDashboard');
Route::get('api/research/{area}/agg/sender/daily', 'ApiSmsController@aggSenderDailyPerArea');

Route::resource('research', 'ResearchController');

Route::resource('research/{researchId}/rules', 'RuleController', ['names' => [
    'store' => 'rules.store',
    'create' => 'rules.create',
    'index' => 'rules.index',
    'update' => 'rules.update'
]]);

Route::resource('research/{researchId}/rules/{ruleId}/questions', 'QuestionController', ['names' => [
    'store' => 'questions.store',
    'create' => 'questions.create',
    'index' => 'questions.index',
    'update' => 'questions.update',
    'edit' => 'questions.edit',
    'destroy' => 'questions.destroy'
]]);

Route::resource('research/{researchId}/rules/{ruleId}/questions/{questionId}/options', 'OptionController', ['names' => [
    'store' => 'options.store',
    'create' => 'options.create',
    'index' => 'options.index',
    'update' => 'options.update',
    'edit' => 'options.edit',
    'destroy' => 'options.destroy'
]]);

Route::get('reports/reports', ['as' => 'reports.reports', 'uses' => 'ReportController@reports']);
Route::get('reports/{id}/approve', ['as' => 'reports.approve', 'uses' => 'ReportController@approve']);
Route::resource('reports', 'ReportController');

Route::get('quick-count', ['as' => ' quickcount.index', 'uses' => 'ResearchController@quickCount']);

Route::get('quick-count/qcs/{daerah}', ['as' => ' quickcount.qcs', 'uses' => 'ResearchController@qcs']);

Route::get('quick-count/{daerah}', ['as' => 'quickcount.daerah', 'uses' => 'ResearchController@qcByArea']);

app/Report.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Report extends Model
{
    //

    protected $fillable = [
        'id',
        'sms_id',
        'tanggal',
        'waktu',
        'pesan',
        'pengirim',
        'status'
    ];

    public function sms() {
        return $this->belongsTo('App\Sms');
    }

    public function datapoints() {
        return $this->hasMany('App\Datapoint');
    }
}

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use App\Datapoint;
use App\Report;
use App\Research;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use yajra\Datatables\Datatables;

class ReportController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return view('report.index');
    }

    public function reports()
    {
        $dateArray = array();
        for($i = 0; $i < 7; $i++) {
            $dateArray[] = date('Y-m-d', strtotime('-'.$i.' days'));
        }

        $reports = Report::whereRaw('(tanggal = "'.$dateArray[0]
            .'" OR tanggal = "'.$dateArray[1]
            .'" OR tanggal = "'.$dateArray[2]
            .'" OR tanggal = "'.$dateArray[3]
            .'" OR tanggal = "'.$dateArray[4]
            .'" OR tanggal = "'.$dateArray[5]
            .'" OR tanggal = "'.$dateArray[6].'"
            ) AND status = FALSE')
            ->get();

        return Datatables::of($reports)
            ->addColumn('aksi', function ($report) {
                if ($report->status) {
                    return '<a class="btn btn-sm btn-info" href='.route('reports.edit', $report->id).'><span class="glyphicon glyphicon-pencil"></span></a>';
                } else {
                    return '<a class="btn btn-sm btn-success" href='.route('reports.approve', $report->id).'><span class="glyphicon glyphicon-ok"></span></a>
                        <a class="btn btn-sm btn-info" href='.route('reports.edit', $report->id).'><span class="glyphicon glyphicon-pencil"></span></a>
                        <a class="btn btn-sm btn-danger" href='.route('reports.destroy', $report->id).' data-method="delete" data-token='.csrf_token().' data-confirm="Are you sure?"><span class="glyphicon glyphicon-trash"></span></a>';
                }
            })
            ->addColumn('count', function($report) {
                return count(explode('#', $report->pesan));
            })
            ->editColumn('status', '{{$status ? "Approved" : "Pending"}}')
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('report.create')->with('report', new Report());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $report = Report::find($id);

        return view('report.edit')->with('report', $report);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $report = Report::find($id);

        $report->tanggal = $request->input('tanggal');
        $report->waktu = $request->input('waktu');
        $report->pesan = $request->input('pesan');
        $report->pengirim = $request->input('pengirim');
        $report->status = $request->input('status');

        $report->save();

        return redirect('reports');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $report = Report::findOrFail($id);

        $report->delete();

        return redirect('reports');
    }

    public function approve($id)
    {
        $report = Report::findOrFail($id);
        $report->status = true;
        $report->save();

        $this->parseReport($report);

        return redirect('reports');
    }

    public function parseReport(Report $report)
    {
        $researches = Research::with('rules.questions.options')->get();

        $data = explode('#', $report->pesan);

        foreach ($researches as $research) {
            foreach ($research->rules as $rule) {
                if (strtolower($rule->keyword) === strtolower($data[0])) {
                    $datapoint = Datapoint::where('report_id',$report->id)->first();
                    if(is_null($datapoint)) {
                        $datapoint = $report->datapoints()->create([
                            'kabupaten' => $research->area,
                            'daerah' => $research->area,
                            'tanggal' => $report->tanggal,
                            'research_id' => $research->id
                        ]);

                        foreach ($rule->questions as $question) {
                            if (count($data) >= (int)$question->number + 1) {
                                $answer = $datapoint->answers()->create([
                                    'kuesioner_id' => (int)$data[1],
                                    'pertanyaan_id' => (int)$question->number,
                                    'jawaban' => $data[(int)$question->number + 1],
                                    'deskripsi' => ''
                                ]);
                            }
                        }
                    }
                }
            }
        }
    }
}

resources/views/report/create.blade.php
@extends('app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Tambah Report
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/reports"><i class="fa fa-dashboard"></i> Report</a></li>
        <li class="active">Tambah</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <!-- Main row -->
    <div class="row">
        <!-- Left col -->
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Detail Report</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                    {!! BootForm::open()->action( route('reports.store', $report) )->post() !!}
                    {!! BootForm::bind($report) !!}
                    {!! BootForm::text('Tanggal', 'tanggal')->placeholder('YYYY-MM-DD') !!}
                    {!! BootForm::text('Waktu', 'waktu')->placeholder('HH:MM:SS') !!}
                    {!! BootForm::text('Pesan', 'pesan') !!}
                    {!! BootForm::text('Pengirim', 'pengirim')->placeholder('+628123456789') !!}
                    {!! BootForm::checkbox('Approved', 'status') !!}
                    {!! BootForm::submit('Simpan') !!}
                    {!! BootForm::close() !!}
                </div>

            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->
@stop

resources/views/report/edit.blade.php
@extends('app')

@section('content')
        <!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Edit Report
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/reports"><i class="fa fa-dashboard"></i> Report</a></li>
        <li class="active">Edit</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <!-- Main row -->
    <div class="row">
        <!-- Left col -->
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Detail Report</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                    {!! BootForm::open()->action( route('reports.update', $report) )->put() !!}
                    {!! BootForm::bind($report) !!}
                    {!! BootForm::text('Tanggal', 'tanggal') !!}
                    {!! BootForm::text('Waktu', 'waktu') !!}
                    {!! BootForm::text('Pesan', 'pesan') !!}
                    {!! BootForm::text('Pengirim', 'pengirim') !!}
                    {!! BootForm::checkbox('Approved', 'status') !!}
                    {!! BootForm::submit('Simpan') !!}
                    {!! BootForm::close() !!}
                </div>

            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->
@stop

resources/views/report/index.blade.php
@extends('app')

@section('content')
        <!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Report
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Report</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <!-- Main row -->
    <div class="row">
        <!-- Left col -->
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Daftar Report</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div class="table-responsive">
                        <table class="table" id="reports-table">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Tanggal</th>
                                <th>Pesan</th>
                                <th>Count</th>
                                <th>Pengirim</th>
                                <th>Status</th>
                                <th>Aksi</th>
                            </tr>
                            </thead>

                        </table>
                    </div>
                </div><!-- /.box-body -->
                <div class="box-footer">
                    <a href={{ route('reports.create') }} class="btn btn-primary">Tambah Report</a>
                </div>
            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->

@push('scripts')
<script>
    $(function() {
        var table = $('#reports-table').DataTable({
            processing: true,
            serverSide: true,
            order: [[ 0, "desc" ]],
            ajax: {
                url: '{!! route('reports.reports') !!}'
            },
            columns: [
                { data: 'id', name: 'id' },
                { data: 'tanggal', name: 'tanggal' },
                { data: 'pesan', name: 'pesan' },
                { data: 'count', name: 'count' },
                { data: 'pengirim', name: 'pengirim' },
                { data: 'status', name: 'status' },
                { data: 'aksi', name: 'aksi' }
            ]
        });
    });
</script>
@endpush

@stop