app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');

Route::get('/dashboard', [
    'middleware' => 'auth',
    'uses' => 'DashboardController@index'
]);

Route::get('/callback', [
    'middleware' => 'auth',
    'uses' => 'DashboardController@callback'
]);

Route::get('/dashboard/ddc', [
    'middleware' => 'auth',
    'uses' => 'DashboardController@ddc'
]);

Route::get('/dashboard/survey', [
    'middleware' => 'auth',
    'uses' => 'DashboardController@survey'
]);

Route::get('/dashboard/survey/{daerah}', [
    'middleware' => 'auth',
    'uses' => 'DashboardController@surveyByDaerah'
]);

Route::get('/dashboard/ddc/test', [
    'middleware' => 'auth',
    'uses' => 'DashboardController@ddctest'
]);

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

Route::resource('sms', 'SmsController');

Route::get('api/sms/all', 'ApiSmsController@index');
Route::get('api/sms/read', 'ApiSmsController@read');
Route::get('api/sms/unread', 'ApiSmsController@unread');
Route::get('api/sms/{area}/daily', 'ApiSmsController@dailySms');
Route::post('api/sms/new', 'ApiSmsController@newSms');
Route::get('api/sms/new', 'ApiSmsController@newSms');

Route::get('api/ddc/aggregates', 'ApiSmsController@aggregates');
Route::get('api/ddc/aggregates/{questionId}','ApiSmsController@aggByQuestionId');
Route::get('api/ddc/aggregates/sender{format?}', 'ApiSmsController@aggSender');
Route::get('api/ddc/aggregates/sender/daily', 'ApiSmsController@aggSenderDaily');
Route::get('api/ddc/aggregates/sender/daily/graph', 'ApiSmsController@aggSenderDailyGraph');
Route::get('api/ddc/aggregates/sender/{date}', 'ApiSmsController@aggSenderWithDate');
Route::get('api/ddc/aggregates/bydate', 'ApiSmsController@aggByDate');

Route::get('api/survey/{daerah}/aggregates', 'ApiSmsController@surveyAggByDaerah');

Route::get('api/survey/{daerah}/dashboard/agg/{nomor}', 'ApiSmsController@surveyAggForDashboard');
Route::get('api/survey/{daerah}/dashboard/sms', 'ApiSmsController@surveySmsForDashboard');
Route::get('api/survey/{daerah}/dashboard/sender', 'ApiSmsController@surveySenderForDashboard');
Route::get('api/survey/{daerah}/dashboard/percentage', 'ApiSmsController@surveyPercentageForDashboard');
Route::get('api/survey/{daerah}/dashboard/gauge', 'ApiSmsController@surveyForDashboardGauge');
Route::get('api/survey/{daerah}/dashboard/{nomor}', 'ApiSmsController@surveyForDashboard');

Route::get('api/research/{id}/dashboard/gauge', 'ApiSmsController@researchForDashboardGauge');
Route::get('api/research/{id}/dashboard/{nomor}', 'ApiSmsController@researchForDashboard');
Route::get('api/research/{area}/agg/sender/daily', 'ApiSmsController@aggSenderDailyPerArea');

Route::resource('research', 'ResearchController');

Route::resource('research/{researchId}/rules', 'RuleController', ['names' => [
    'store' => 'rules.store',
    'create' => 'rules.create',
    'index' => 'rules.index',
    'update' => 'rules.update'
]]);

Route::resource('research/{researchId}/rules/{ruleId}/questions', 'QuestionController', ['names' => [
    'store' => 'questions.store',
    'create' => 'questions.create',
    'index' => 'questions.index',
    'update' => 'questions.update',
    'edit' => 'questions.edit',
    'destroy' => 'questions.destroy'
]]);

Route::resource('research/{researchId}/rules/{ruleId}/questions/{questionId}/options', 'OptionController', ['names' => [
    'store' => 'options.store',
    'create' => 'options.create',
    'index' => 'options.index',
    'update' => 'options.update',
    'edit' => 'options.edit',
    'destroy' => 'options.destroy'
]]);

Route::get('reports/reports', ['as' => 'reports.reports', 'uses' => 'ReportController@reports']);
Route::get('reports/{id}/approve', ['as' => 'reports.approve', 'uses' => 'ReportController@approve']);
Route::resource('reports', 'ReportController');

Route::get('quick-count', ['as' => ' quickcount.index', 'uses' => 'ResearchController@quickCount']);

Route::get('quick-count/qcs/{daerah}', ['as' => ' quickcount.qcs', 'uses' => 'ResearchController@qcs']);

Route::get('quick-count/{daerah}', ['as' => 'quickcount.daerah', 'uses' => 'ResearchController@qcByArea']);

app/Research.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Research extends Model
{
    protected $fillable = [
        'title',
        'type',
        'area',
        'start_date',
        'end_date',
        'user_id'
    ];

    public function rules()
    {
        return $this->hasMany('App\Rule');
    }

    public function datapoints()
    {
        return $this->hasMany('App\Datapoint');
    }

    public function persons()
    {
        return $this->hasMany('App\Person');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/ResearchController.php
<?php

namespace App\Http\Controllers;

use App\Report;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Research;
use App\Person;
use Auth;
use yajra\Datatables\Datatables;

class ResearchController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $researches = Research::all();

        return view('research.index')->with('researches', $researches);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('research.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        $research = Auth::user()->researches()->create($request->all());;

        return redirect('research');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        return view('research.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $research = Research::findOrFail($id);

        return view('research.edit')->with('research', $research);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $research = Research::findOrFail($id);

        $research->update($request->all());

        return redirect('research');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $research = Research::findOrFail($id);
        $research->delete();

        return redirect('research');
    }

    public function quickCount()
    {
        return view('qc.index');
    }

    public function qcs($daerah)
    {
        $kota = [
            'bateng' => 'Bangka Tengah',
            'babar' => 'Bangka Barat',
            'basel' => 'Bangka Selatan',
            'beltim' => 'Belitung Timur',
            'kutim' => 'Kutai Timur'
        ];

        $persons = Person::where(['persons.kota' => $kota[$daerah]])
            ->leftJoin('reports', 'reports.pengirim', '=', 'persons.hp')
            ->select('persons.id', 'persons.hp', 'persons.nama', 'persons.alamat', 'reports.id as report_id', 'reports.pesan', 'reports.waktu', 'reports.status');

        return Datatables::of($persons)
            ->addColumn('aksi', function ($person) {
                if ($person->status === 1) {
                    return '<a class="btn btn-sm btn-success" href=' . route('reports.approve', $person->report_id) . '><span class="glyphicon glyphicon-ok"></span></a>
                        <a class="btn btn-sm btn-info" href=' . route('reports.edit', $person->report_id) . '><span class="glyphicon glyphicon-pencil"></span></a>';
                } else {
                    return '<a class="btn btn-sm btn-primary" href=' . route('reports.create') . '><span class="glyphicon glyphicon-plus"></span></a>';
                }
            })
            ->addColumn('count', function($person) {
                if (count_chars($person->pesan) > 1) {
                    return count(explode('#', $person->pesan));
                } else {
                    return 0;
                }
            })
            ->addColumn('status', function($person) {
                if (is_null($person->status)) {
                    return '';
                } else {
                    $status = array('Pending', 'Approved');
                    return $status[$person->status];
                }
            })
            ->make(true);
    }

    public function qcByArea($daerah) {
        $area = [
            'bateng' => 'Bangka Tengah',
            'basel' => 'Bangka Selatan',
            'babar' => 'Bangka Barat',
            'beltim' => 'Belitung Timur',
            'kutim' => 'Kutai Timur'
        ];

        return view ('qc.daerah')->with(['daerah' => $daerah, 'area' => $area[$daerah]]);
    }
}

resources/views/research/create.blade.php
@extends('app')

@section('content')
        <!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Tambah Riset
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/research"><i class="fa fa-dashboard"></i> Riset</a></li>
        <li class="active">Tambah</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <!-- Main row -->
    <div class="row">
        <!-- Left col -->
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Daftar Riset</h3>
                </div><!-- /.box-header -->

                {!! BootForm::open()->action( route('research.store', $research = new App\Research) )->post() !!}
                {!! BootForm::bind($research) !!}
                    <div class="box-body">
                        @include('research.form', ['submitButtonText' => 'Tambah Riset'])
                    </div><!-- /.box-body -->
                {!! BootForm::close() !!}
            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->
@stop

resources/views/research/edit.blade.php
@extends('app')

@section('content')
        <!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Tambah Riset
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/research"><i class="fa fa-dashboard"></i> Riset</a></li>
        <li class="active">Tambah</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <!-- Main row -->
    <div class="row">
        <!-- Left col -->
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Daftar Riset</h3>
                </div><!-- /.box-header -->

                {!! BootForm::open()->action( route('research.update', $research) )->put() !!}
                {!! BootForm::bind($research) !!}
                <div class="box-body">
                    @include('research.form', ['submitButtonText' => 'Simpan Riset'])
                </div><!-- /.box-body -->
                {!! BootForm::close() !!}
            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->
@stop

resources/views/research/form.blade.php
{!! BootForm::text('Judul', 'title')->placeholder('Judul riset') !!}
{!! BootForm::select('Tipe', 'type')->options(['survey' => 'Survei', 'ddc' => 'DDC', 'quickcount' => 'Quick Count', 'realcount' => 'Real Count'])->select('survey'); !!}
{!! BootForm::text('Daerah', 'area')->placeholder('Daerah tempat riset') !!}
{!! BootForm::text('Tanggal Mulai', 'start_date')->placeholder('YYYY-MM-DD. Contoh: 2015-12-31.') !!}
{!! BootForm::text('Tanggal Berakhir', 'end_date')->placeholder('YYYY-MM-DD. Contoh: 2015-12-31.') !!}
{!! BootForm::submit($submitButtonText) !!}

resources/views/research/index.blade.php
@extends('app')

@section('content')
        <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Riset
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Riset</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <div class="col-md-12">
                <div class="box box-info">
                    <div class="box-header">
                        <h3 class="box-title">Daftar Riset</h3>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                                <div class="table-responsive">
                                    <table class="table">
                                        <tr>
                                            <th>Nomor</th>
                                            <th>Judul</th>
                                            <th>Tipe</th>
                                            <th>Daerah</th>
                                            <th>Mulai</th>
                                            <th>Selesai</th>
                                            <th>Aksi</th>
                                        </tr>
                                        @foreach($researches as $key => $research)
                                            <tr>
                                                <td>{{ $key+1 }}</td>
                                                <td>{{ $research->title }}</td>
                                                <td>{{ $research->type }}</td>
                                                <td>{{ $research->area }}</td>
                                                <td>{{ $research->start_date }}</td>
                                                <td>{{ $research->end_date }}</td>
                                                <td>
                                                    <a class="btn btn-success" href={{ url('research/'.$research->id.'/rules') }}>Aturan</a>
                                                    <a class="btn btn-info" href="/research/{{ $research->id }}/edit">Edit</a>
                                                    <a href={{ url('research/'.$research->id) }} data-method="delete" data-token="{{csrf_token()}}" data-confirm="Anda yakin akan menghapus kuis?" class="btn btn-danger">Hapus</a>
                                                    @if ($research->area == "KUTIM") <a class="btn btn-warning" href="https://app.cyfe.com/dashboards/259425/tv" target="_blank">Display</a>@endif
                                                </td>
                                            </tr>
                                        @endforeach
                                    </table>
                                </div>
                    </div><!-- /.box-body -->
                    <div class="box-footer">
                        <a href="/research/create" class="btn btn-success">Tambah Riset</a>
                    </div>
                </div><!-- /.box -->
            </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
@stop

resources/views/research/show.blade.php
@extends('app')

@section('content')
        <!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Dashboard
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <!-- Main row -->
    <div class="row">
        <!-- Left col -->
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">SMS Masuk</h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" ng-click="polSmsCtrl.getSms()"><i class="fa fa-refresh"></i></button>
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div ui-grid="polSmsCtrl.allSmsGrid" class="todaySmsTable"></div>
                    <br>
                    <div ui-grid="polSmsCtrl.allSmsDailyGrid" class="todaySmsDailyTable"></div>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">SMS Harian Per Relawan</h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" ng-click="polSmsCtrl.getSenderAggregatesDaily()"><i class="fa fa-refresh"></i></button>
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div ui-grid="polSmsCtrl.volSmsDailyGrid" class="volunteerSmsDailyTable"></div>
                </div><!-- /.box-body -->
                <div class="box-footer clearfix">
                    <div class="row">
                        <div class="col-xs-3">
                            <select class="form-control pull-right" required="true" ng-model="polSmsCtrl.dailySenderAggOption">
                                <option value="all" selected>Semua</option>
                                <option value="kutim">DDC - Kutim</option>
                                <option value="bateng">DDC - Bateng</option>
                                <option value="bateng">Survey - Bateng</option>
                                <option value="kutim">Survey - Kutim</option>
                                <option value="karawang">Survey - Karawang</option>
                                <option value="nasional">Survey - Nasional</option>
                                <option value="basel">Survey - Basel</option>
                                <option value="babar">Survey - Babar</option>
                            </select>
                        </div>
                        <div class="col-xs-3">
                            <button class="btn btn-default" ng-click="polSmsCtrl.getSenderAggregatesDaily()"><i class="fa fa-refresh"></i></button>
                        </div>
                    </div>
                </div><!-- /.box-footer -->
            </div><!-- /.box -->
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Callback Ticketing</h3>
                </div>
                <div class="box-body">
                    <iframe src="https://docs.google.com/spreadsheets/d/1RsnYs1CZH7uRlAL4BOLkQCUCx4XdocKBMrL-pZ3SbeE/edit?usp=sharing" width="100%" height="500px"></iframe>
                </div>
            </div>
        </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->
@stop