app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');

Route::get('/dashboard', [
    'middleware' => 'auth',
    'uses' => 'DashboardController@index'
]);

Route::get('/callback', [
    'middleware' => 'auth',
    'uses' => 'DashboardController@callback'
]);

Route::get('/dashboard/ddc', [
    'middleware' => 'auth',
    'uses' => 'DashboardController@ddc'
]);

Route::get('/dashboard/survey', [
    'middleware' => 'auth',
    'uses' => 'DashboardController@survey'
]);

Route::get('/dashboard/survey/{daerah}', [
    'middleware' => 'auth',
    'uses' => 'DashboardController@surveyByDaerah'
]);

Route::get('/dashboard/ddc/test', [
    'middleware' => 'auth',
    'uses' => 'DashboardController@ddctest'
]);

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

Route::resource('sms', 'SmsController');

Route::get('api/sms/all', 'ApiSmsController@index');
Route::get('api/sms/read', 'ApiSmsController@read');
Route::get('api/sms/unread', 'ApiSmsController@unread');
Route::get('api/sms/{area}/daily', 'ApiSmsController@dailySms');
Route::post('api/sms/new', 'ApiSmsController@newSms');
Route::get('api/sms/new', 'ApiSmsController@newSms');

Route::get('api/ddc/aggregates', 'ApiSmsController@aggregates');
Route::get('api/ddc/aggregates/{questionId}','ApiSmsController@aggByQuestionId');
Route::get('api/ddc/aggregates/sender{format?}', 'ApiSmsController@aggSender');
Route::get('api/ddc/aggregates/sender/daily', 'ApiSmsController@aggSenderDaily');
Route::get('api/ddc/aggregates/sender/daily/graph', 'ApiSmsController@aggSenderDailyGraph');
Route::get('api/ddc/aggregates/sender/{date}', 'ApiSmsController@aggSenderWithDate');
Route::get('api/ddc/aggregates/bydate', 'ApiSmsController@aggByDate');

Route::get('api/survey/{daerah}/aggregates', 'ApiSmsController@surveyAggByDaerah');

Route::get('api/survey/{daerah}/dashboard/agg/{nomor}', 'ApiSmsController@surveyAggForDashboard');
Route::get('api/survey/{daerah}/dashboard/sms', 'ApiSmsController@surveySmsForDashboard');
Route::get('api/survey/{daerah}/dashboard/sender', 'ApiSmsController@surveySenderForDashboard');
Route::get('api/survey/{daerah}/dashboard/percentage', 'ApiSmsController@surveyPercentageForDashboard');
Route::get('api/survey/{daerah}/dashboard/gauge', 'ApiSmsController@surveyForDashboardGauge');
Route::get('api/survey/{daerah}/dashboard/{nomor}', 'ApiSmsController@surveyForDashboard');

Route::get('api/research/{id}/dashboard/gauge', 'ApiSmsController@researchForDashboardGauge');
Route::get('api/research/{id}/dashboard/{nomor}', 'ApiSmsController@researchForDashboard');
Route::get('api/research/{area}/agg/sender/daily', 'ApiSmsController@aggSenderDailyPerArea');

Route::resource('research', 'ResearchController');

Route::resource('research/{researchId}/rules', 'RuleController', ['names' => [
    'store' => 'rules.store',
    'create' => 'rules.create',
    'index' => 'rules.index',
    'update' => 'rules.update'
]]);

Route::resource('research/{researchId}/rules/{ruleId}/questions', 'QuestionController', ['names' => [
    'store' => 'questions.store',
    'create' => 'questions.create',
    'index' => 'questions.index',
    'update' => 'questions.update',
    'edit' => 'questions.edit',
    'destroy' => 'questions.destroy'
]]);

Route::resource('research/{researchId}/rules/{ruleId}/questions/{questionId}/options', 'OptionController', ['names' => [
    'store' => 'options.store',
    'create' => 'options.create',
    'index' => 'options.index',
    'update' => 'options.update',
    'edit' => 'options.edit',
    'destroy' => 'options.destroy'
]]);

Route::get('reports/reports', ['as' => 'reports.reports', 'uses' => 'ReportController@reports']);
Route::get('reports/{id}/approve', ['as' => 'reports.approve', 'uses' => 'ReportController@approve']);
Route::resource('reports', 'ReportController');

Route::get('quick-count', ['as' => ' quickcount.index', 'uses' => 'ResearchController@quickCount']);

Route::get('quick-count/qcs/{daerah}', ['as' => ' quickcount.qcs', 'uses' => 'ResearchController@qcs']);

Route::get('quick-count/{daerah}', ['as' => 'quickcount.daerah', 'uses' => 'ResearchController@qcByArea']);

app/Option.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Option extends Model
{
    protected $fillable = [
        'description',
        'number',
        'question_id'
    ];

    public function answers()
    {
        return $this->hasMany('App\Answer');
    }

    public function question()
    {
        return $this->belongsTo('App\Question');
    }
}

app/Http/Controllers/OptionController.php
<?php

namespace App\Http\Controllers;

use App\Option;
use App\Question;
use App\Rule;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class OptionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($researchId, $ruleId, $questionId)
    {
        $question = Question::find($questionId);

        $options = Question::find($questionId)->options()->get();

        return view('option.index')->with(['options' => $options, 'researchId' => $researchId, 'ruleId' => $ruleId, 'question' => $question]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($researchId, $ruleId, $questionId)
    {
        $question = Question::find($questionId);

        return view('option.create')->with(['researchId' => $researchId, 'ruleId' => $ruleId, 'question' => $question]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store($researchId, $ruleId, $questionId, Request $request)
    {
        $option = Question::find($questionId)->options()->create($request->all());;

        return redirect('research/'.$researchId.'/rules/'.$ruleId.'/questions/'.$questionId.'/options');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($researchId, $ruleId, $questionId, $id)
    {
        $question = Question::find($questionId);

        $option = Option::find($id);

        return view('option.edit')->with(['researchId' => $researchId, 'ruleId' => $ruleId, 'question' => $question, 'option' => $option]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update($researchId, $ruleId, $questionId, Request $request, $id)
    {
        $option = Option::find($id)->update($request->all());

        return redirect('research/'.$researchId.'/rules/'.$ruleId.'/questions/'.$questionId.'/options');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($researchId, $ruleId, $questionId, $id)
    {
        $option = Option::find($id)->delete();

        return redirect('research/'.$researchId.'/rules/'.$ruleId.'/questions/'.$questionId.'/options');
    }
}

resources/views/option/create.blade.php
@extends('app')

@section('content')
        <!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Tambah Pilihan Jawaban
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href={{ route('research.index', ['researchId' => $researchId, 'ruleId' => $ruleId, 'questionId' => $question->id]) }}>Riset</a></li>
        <li><a href={{ route('rules.index', ['researchId' => $researchId, 'ruleId' => $ruleId, 'questionId' => $question->id]) }}>Aturan</a></li>
        <li><a href={{ route('questions.index', ['researchId' => $researchId, 'ruleId' => $ruleId, 'questionId' => $question->id]) }}>Pertanyaan</a></li>
        <li><a href={{ route('options.index', ['researchId' => $researchId, 'ruleId' => $ruleId, 'questionId' => $question->id]) }}>Pilihan Jawaban</a></li>
        <li class="active">Tambah Pilihan</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <!-- Main row -->
    <div class="row">
        <!-- Left col -->
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">{{ $question->description }}</h3>
                </div><!-- /.box-header -->

                {!! BootForm::open()->action( route('options.store', ['researchId' => $researchId, 'ruleId' => $ruleId, 'questionId' => $question->id], $option = new App\Option) )->post() !!}
                {!! BootForm::bind($option) !!}
                <div class="box-body">
                    @include('option.form', ['submitButtonText' => 'Tambah Pilihan'])
                </div><!-- /.box-body -->
                {!! BootForm::close() !!}
            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->
@stop

resources/views/option/edit.blade.php
@extends('app')

@section('content')
        <!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Ubah Pilihan Jawaban
    </h1>
    <ol class="breadcrumb">
        <li><a href={{ route('research.index', ['researchId' => $researchId, 'ruleId' => $ruleId, 'questionId' => $question->id]) }}>Riset</a></li>
        <li><a href={{ route('rules.index', ['researchId' => $researchId, 'ruleId' => $ruleId, 'questionId' => $question->id]) }}>Aturan</a></li>
        <li><a href={{ route('questions.index', ['researchId' => $researchId, 'ruleId' => $ruleId, 'questionId' => $question->id]) }}>Pertanyaan</a></li>
        <li><a href={{ route('options.index', ['researchId' => $researchId, 'ruleId' => $ruleId, 'questionId' => $question->id]) }}>Pilihan Jawaban</a></li>
        <li class="active">Ubah Pilihan</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <!-- Main row -->
    <div class="row">
        <!-- Left col -->
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">{{ $question->description }}</h3>
                </div><!-- /.box-header -->

                {!! BootForm::open()->action( route('options.update', ['researchId' => $researchId, 'ruleId' => $ruleId, 'questionId' => $question->id, 'id' => $option->id], $option) )->put() !!}
                {!! BootForm::bind($option) !!}
                <div class="box-body">
                    @include('option.form', ['submitButtonText' => 'Simpan Pilihan'])
                </div><!-- /.box-body -->
                {!! BootForm::close() !!}
            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->
@stop

resources/views/option/form.blade.php
{!! BootForm::text('Nomor pilihan', 'number')->placeholder('Isi dengan nomor pilihan') !!}
{!! BootForm::textarea('Deskripsi jawaban', 'description')->rows(5) !!}
{!! BootForm::submit($submitButtonText) !!}

resources/views/option/index.blade.php
@extends('app')

@section('content')
        <!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Pilihan Jawaban
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href={{ route('research.index', ['researchId' => $researchId, 'ruleId' => $ruleId, 'questionId' => $question->id]) }}>Riset</a></li>
        <li><a href={{ route('rules.index', ['researchId' => $researchId, 'ruleId' => $ruleId, 'questionId' => $question->id]) }}>Aturan</a></li>
        <li><a href={{ route('questions.index', ['researchId' => $researchId, 'ruleId' => $ruleId, 'questionId' => $question->id]) }}>Pertanyaan</a></li>
        <li class="active">Pilihan jawaban</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <!-- Main row -->
    <div class="row">
        <!-- Left col -->
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">{{ $question->description }}</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div class="table-responsive">
                        <table class="table">
                            <tr>
                                <th>Nomor</th>
                                <th>Deskripsi jawaban</th>
                                <th>Tipe</th>
                            </tr>
                            @foreach($options as $key => $option)
                                <tr>
                                    <td>{{ $option->number }}</td>
                                    <td>{{ $option->description }}</td>
                                    <td>
                                        <a class="btn btn-info" href={{ route('options.edit', ['researchId' => $researchId, 'ruleId' => $ruleId, 'questionId' => $question->id, 'id' => $option->id]) }}>Edit</a>
                                        <a href={{ route('options.destroy', ['researchId' => $researchId, 'ruleId' => $ruleId, 'questionId' => $question->id, 'id' => $option->id]) }} data-method="delete" data-token="{{csrf_token()}}" data-confirm="Anda yakin akan menghapus pilihan?" class="btn btn-danger">Hapus</a>
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                </div><!-- /.box-body -->
                <div class="box-footer">
                    <a href={{ route('options.create', ['researchId' => $researchId, 'ruleId' => $ruleId, 'questionId' => $question->id]) }} class="btn btn-default">Tambah pilihan</a>
                </div>
            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->
@stop